name: bamboukreyol
description: Application d'informations pour les membres de l'association Bambou Kreyol
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_flavorizr: ^2.2.1
  go_router: ^8.0.5
  google_fonts: ^5.0.0
  firebase_core: ^2.14.0
  firebase_core_platform_interface: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo_bk.png
    - assets/logo_bk_white.jpg

